# Section 3: Natural Language Processing (NLP)

### Task 4: Sentiment Analysis (NLP)

In [4]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [5]:
import pandas as pd

In [6]:
df=pd.read_csv('../datasets/sentiment_analysis.csv')
df

,Year,Month,Day,Time of Tweet,text,sentiment,Platform
0,2018,8,18,morning,What a great day!!! Looks like dream.,positive,Twitter
1,2018,8,18,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook
2,2017,8,18,night,Don't angry me,negative,Facebook
3,2022,6,8,morning,We attend in the class just for listening teac...,negative,Facebook
4,2022,6,8,noon,"Those who want to go, let them go",negative,Instagram
...,...,...,...,...,...,...,...
494,2015,10,18,night,"According to , a quarter of families under six...",negative,Twitter
495,2021,2,25,morning,the plan to not spend money is not going well,negative,Instagram
496,2022,5,30,noon,uploading all my bamboozle pictures of facebook,neutral,Facebook
497,2018,8,10,night,congratulations ! you guys finish a month ear...,positive,Twitter
498,2019,3,25,morning,"actually, I wish I was back in Tahoe. I miss...",negative,Instagram

In [7]:
df=df[['text']]

In [8]:
df

                                                  text
0                What a great day!!! Looks like dream.
1       I feel sorry, I miss you here in the sea beach
2                                       Don't angry me
3    We attend in the class just for listening teac...
4                    Those who want to go, let them go
..                                                 ...
494  According to , a quarter of families under six...
495      the plan to not spend money is not going well
496    uploading all my bamboozle pictures of facebook
497   congratulations ! you guys finish a month ear...
498   actually, I wish I was back in Tahoe.  I miss...

[499 rows x 1 columns]

##### Data Preprocessing:
- Clean the text data (remove stopwords, punctuation, and special characters).
- Convert the text into numerical format using TF-IDF or Word Embedding (e.g.,
Word2Vec).

In [9]:
stop_words = set(stopwords.words("english"))

df["text"] = df["text"].fillna("").astype(str)
df["text"] = df["text"].apply(lambda x: re.sub(r"[^a-zA-Z0-9\s-]+", "", x))
df["text"] = df["text"].apply(lambda x: " ".join([w for w in x.split() if w.lower() not in stop_words]))

C:\Users\Admin\AppData\Local\Temp\ipykernel_7428\1246582465.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text"] = df["text"].fillna("").astype(str)
C:\Users\Admin\AppData\Local\Temp\ipykernel_7428\1246582465.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text"] = df["text"].apply(lambda x: re.sub(r"[^a-zA-Z0-9\s-]+", "", x))
C:\Users\Admin\AppData\Local\Temp\ipykernel_7428\1246582465.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text"] = df["text"].apply(lambda x: " ".join([w for w in x.split() if w.lower() not in stop_words]))

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [11]:
tfv=TfidfVectorizer()
X=tfv.fit_transform(df['text'])

In [12]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3110 stored elements and shape (499, 1304)>

##### Tasks:
- Build a sentiment analysis model to classify text as Positive or Negative.
- Split the dataset into training and testing sets.
- Train a classification model using any of the following:
  Simple RNN
  LSTM RNN
- Evaluate the model using accuracy, precision, recall, and F1 score.

##### NULL

-------------------------------------------------------------------------------------------------------